# Generated by Django 5.0 on 2023-12-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper', models.IntegerField()),
                ('band', models.IntegerField()),
                ('firmness', models.IntegerField()),
                ('oils', models.IntegerField()),
                ('light', models.IntegerField()),
                ('burn', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('consistency', models.IntegerField()),
                ('flavor', models.IntegerField()),
                ('smoothness', models.IntegerField()),
                ('blend', models.IntegerField()),
                ('progression', models.IntegerField()),
                ('finish', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('price', models.IntegerField()),
                ('overall', models.IntegerField()),
            ],
        ),
    ]
