# Generated by Django 5.0 on 2023-12-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0001_initial'),
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='cigar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cigar.cigar'),
            preserve_default=False,
        ),
    ]
