# Generated by Django 5.0 on 2023-12-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0003_alter_cigar_gauge_alter_cigar_length'),
        ('scores', '0003_alter_scores_cigar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='cigar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cigar.cigar'),
            preserve_default=False,
        ),
    ]
