# Generated by Django 5.0 on 2023-12-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('scores', '0004_alter_scores_cigar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='notes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.notes'),
            preserve_default=False,
        ),
    ]
