# Generated by Django 5.0 on 2023-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigar',
            name='gauge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cigar',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
