# Generated by Django 5.0 on 2023-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigar', '0002_cigar_gauge_cigar_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigar',
            name='gauge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cigar',
            name='length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
