# Generated by Django 5.0 on 2023-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_third', models.CharField(max_length=255)),
                ('second_third', models.CharField(max_length=255)),
                ('final_third', models.CharField(max_length=255)),
                ('overall', models.CharField(max_length=255)),
            ],
        ),
    ]
